config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  get :searcher, to: 'home#searcher'

  resources :categories, only: :show
  resources :scraper, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category

  scope :by_category, ->(category) { where(category: category) }
  scope :recents, ->(number) { order(id: :desc).limit(number) }

  validates_uniqueness_of :link, on: :create, message: 'Já existe...'

  def self.new_blank
    new(
      title: 'Nenhum post encontrado!',
      link: '/scraper?token=lKtT7jYxE_KX1TZmLRfGAw',
      cover_link: '/blank.png'
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def set_collection
    @categories = Category.all.order(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_collection

  def show
    @category = Category.find_by(id: params[:id])
    @posts = scope_post(20, params[:id])
  end

  private

  def scope_post(limit = 9, category = nil)
    scope = Post.order(id: :desc).limit(limit)
    scope = scope.by_category(category) if category
    scope
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_collection

  def index
    @highlight_post = Post.last || Post.new_blank
    @recent_posts = scope_post(9).where.not(id: @highlight_post)
  end

  def searcher
    @q = Post.ransack(title_cont: params[:q])
    @posts = @q.result(distinct: true).order(id: :desc).limit(20)
  end

  private

  def scope_post(limit = 9, category = nil)
    scope = Post.order(id: :desc).limit(limit)
    scope = scope.by_category(category) if category
    scope
  end
end

app/controllers/scraper_controller.rb
class ScraperController < ApplicationController
  def index
    return redirect_to '/404.html' if token_invalid?

    Scraper.run

    render json: { status: 'ok' }, status: :ok
  end

  private

  def token_invalid?
    params[:token].blank? || params[:token] != ENV['THE_WILL_TOKEN']
  end
end

app/controllers/scrapper_controller.rb
class ScraperController < ApplicationController
  def index
    return redirect_to '/404.html' if token_invalid?

    Scraper.run

    render text: 'ok'
  end

  private

  def token_invalid?
    params[:token].blank? || params[:token] != ENV['THE_WILL_TOKEN']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/string_helper.rb
# frozen_string_literal: true

# Helpers de ajuda para exibir dados nas viewa
module StringHelper
  include ActionView::Helpers::NumberHelper

  # Formata data ou retorna string vazia caso nao receba uma valor
  def format_date(data, mascara = '%d/%m/%Y', blank_value = '-')
    return blank_value if data.blank?

    data.to_date.in_time_zone.strftime(mascara)
  end

  # Formata data ou retorna string vazia caso nao receba uma valor
  def format_datetime(data, mascara = '%d/%m/%Y às %H:%Mh', blank_value = '-')
    return blank_value if data.blank?

    data.in_time_zone.strftime(mascara)
  end

  # Formata booleano para SIM|NAO
  def format_boolean(valor)
    t("booleans.#{valor}")
  end

  def encode_uri(text)
    ERB::Util.url_encode(text.to_s)
  end
end

app/views/categories/show.haml
= render 'home/post_list', posts: @posts, title1: "Resultados para:", title2: @category.try(:name)

app/views/home/_highlight_post.haml
.row.mb-5
  .col-md-6
    = link_to @highlight_post.link, class: 'post-link', target: '_blank' do
      %img.cover-highlight.cover{'data-src': @highlight_post.cover_link, alt: @highlight_post.title, style: 'min-heigth: 400px;'}

  .col-md-6
    %small.text-muted
      = "#{format_date(@highlight_post.created_at)} - #{@highlight_post.origin.to_s.titleize}"

    %h2.h1
      = link_to @highlight_post.link, class: 'post-link', target: '_blank' do
        = @highlight_post.title

    %p.text-muted
      = @highlight_post.description

    = link_to 'LER NOTÍCIA', @highlight_post.link, class: 'btn btn-primary rounded-pill mb-3', target: '_blank'

    %small.text-muted.d-block= "Atualizado em #{format_datetime(@highlight_post.created_at)}"

    .my-3
      = render 'home/share', post: @highlight_post, align: 'start'

app/views/home/_post_list.haml
.row.my-4
  - if defined? title1
    .col-12.mb-2
      %h3
        = title1
      
        - if defined? title2
          %span.text-primary= title2

  - posts.each do |post|
    .col-md-4.mb-3
      .card.w-100.h-100.card-post.bg-transparent.border-0

        = link_to post.link, class: 'w-100 post-link' do
          %img.card-img-top.cover{'data-src': post.cover_link, alt: post.title}

        .card-body
          .post-data
            %span.text-muted
              = "#{format_date(post.created_at)} - #{post.origin.to_s.titleize}"
            
            %h5.card-title
              = link_to post.link, class: 'post-link' do
                = post.title

            %p.card-text
              = post.description

          .mb-2
            = render 'home/share', post: post

  %hr.my-5

app/views/home/_share.haml
:ruby
  post_url = encode_uri(post.link)
  post_title = encode_uri(post.title)

.post-share.d-flex.d-lg-initial.align-items-center.mt-3.mt-lg-0{class: defined?(align) ? "justify-content-#{align}" : 'justify-content-end'}

  %a.post-share-facebook{href: "https://facebook.com/sharer/sharer.php?u=#{post_url}", target: "_blank"}
    %i.fab.fa-facebook

  %a.post-share-twitter{href: "https://twitter.com/intent/tweet?url=#{post_url}&text=#{post_title}&via=Nerd%20Drops", target: "_blank"}
    %i.fab.fa-twitter

  %a.post-share-telegram{href: "https://telegram.me/share/url?url=#{post_url}&text=#{post_title}&via=Nerd%20Drops", target: "_blank"}
    %i.fab.fa-telegram-plane

  %a.post-share-whatsapp{"data-action": "share/whatsapp/share", href: "https://web.whatsapp.com/send?text=#{post_title}%0A%0A#{post_url}%0A%0Avia Nerd%20Drops", target: "_blank"}
    %i.fab.fa-whatsapp

app/views/home/index.haml
.row
  .col-12
    %h1#the-will-home Nerd Drop
    %p.subtile
      Últimas notícias do mundo nerd agrupas dos melhores sites.

= render 'highlight_post'

= render 'post_list', posts: @recent_posts, title1: 'Mais Recentes'

- @categories.each do |category|
  :ruby
    posts = category.posts.recents(3).where.not(id: @recent_posts.map(&:id) + [@highlight_post.id])
    next if posts.blank?

  = render 'post_list', posts: posts, title1: category.name

app/views/home/searcher.haml
= render 'post_list', posts: @posts, title1: "Resultados para:", title2: params[:q]

app/views/layouts/application.html.haml
!!!
%html{prefix: "og: https://ogp.me/ns#"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/

    %meta{content: "Nerd Drop", name: "apple-mobile-web-app-title"}
    %meta{content: "Nerd Drop", name: "application-name"}
    %meta{content: "#d63384", name: "theme-color"}
    %meta{content: "#ffffff", name: "msapplication-TileColor"}

    %meta{content: "Nerd Drop", property: "og:title"}/
    %meta{content: "Últimas notícias do mundo nerd agrupas dos melhores sites.", property: "og:description"}/
    %meta{content: "website", property: "og:type"}/
    %meta{content: request.url, property: "og:url"}/
    %meta{content: @highlight_post.try(:cover_link) || "#{request.host}/favicons/android-chrome-512x512.png", property: "og:image"}/

    %link{href: "/apple-touch-icon.png", rel: "apple-touch-icon", sizes: "180x180"}
    %link{href: "/favicons/favicon-32x32.png", rel: "icon", sizes: "32x32", type: "image/png"}
    %link{href: "/favicons/favicon-16x16.png", rel: "icon", sizes: "16x16", type: "image/png"}
    %link{href: "/manifest.json", rel: "manifest"}

    %title Nerd Drop

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/navigation/navbar'

    #main-content.container.py-5
      = yield

    %footer.w-100.bg-dark.text-light.py-5.px-3
      .container.text-center
        = "Nerd Drop #{Time.now.strftime('%Y')} -" 
        Desenvolvido por
        = link_to 'Wilfison', 'https://github.com/Wilfison', target: '_blank'

app/views/layouts/navigation/_navbar.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container
    %a.navbar-brand{href: "/"}
      = image_tag 'logo.svg', alt: 'Nerd Drop', height: '28'

    %form.d-flex.mx-auto{action: '/searcher', style: 'max-width: 50%;'}
      %input.form-control.me-2.rounded-pill{"aria-label": "Search", placeholder: "Search", type: "search", name: 'q'}

      %button.btn.btn-light#navbarSearchBtn{type: "submit"}
        %svg.bi.bi-search{fill: "black", height: "16", viewbox: "0 0 16 16", width: "16", xmlns: "http://www.w3.org/2000/svg"}
          %path{d: "M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"}

    %button.navbar-toggler{"aria-controls": "navbarScroll", "aria-expanded": "false", "aria-label": "Toggle navigation", "data-bs-target": "#navbarScroll", "data-bs-toggle": "collapse", type: "button"}
      %span.navbar-toggler-icon

    #navbarScroll.collapse.navbar-collapse.ml-auto
      %ul.navbar-nav.my-2.my-lg-0.navbar-nav-scroll
        %li.nav-item
          %a.nav-link.active{"aria-current": "page", href: "/"} Home
        %li.nav-item.dropdown
          %a#navbarCategoryDrop.nav-link.dropdown-toggle{"aria-expanded": "false", "data-bs-toggle": "dropdown", href: "#", role: "button"}
            Categorias
          %ul.dropdown-menu{"aria-labelledby": "navbarCategoryDrop"}
            - @categories.each do |category|
              %li
                = link_to category.name, category_path(category), class: 'dropdown-item'